{
 "title": "cPanel Metrics (Business Identity)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "cPanel",
    "query": "SELECT DISTINCT(\"url\") FROM (SELECT * FROM \"cpanel_meta\" WHERE $timeFilter GROUP BY \"url\")"
   },
   {
    "name": "cpanel_user",
    "label": "cPanel User",
    "query": "SELECT \"user\" FROM (SELECT MAX(gauge),\"url\" FROM \"cpanel_bandwidth\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP by \"user\")"
   }
  ]
 },
 "panels": [
  { "title": "Tips", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Servers Selected",
     "type": "table",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 29 },
     "targets": [
      {
       "query": "SELECT DISTINCT(\"url\") as \"Metric URL\" FROM (SELECT * FROM \"cpanel_meta\" WHERE $timeFilter AND (\"url\" =~ /^$instance$/) GROUP BY \"url\")"
      }
     ]
    },
    {
     "title": "cPanel Server Started Time Ago",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpanel_start_time_unix_timestamp",
       "query": "SELECT last(\"gauge\") * 1000 FROM \"cpanel_start_time_unix_timestamp\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), url fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "* 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Started Date List",
     "type": "table",
     "description": "Show as table, incase multiple cPanel servers are listed to be viewed",
     "gridPos": { "h": 5, "w": 10, "x": 5, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpanel_start_time_unix_timestamp",
       "query": "SELECT (last(gauge) * 1000) as \"Start Time\" FROM \"cpanel_start_time_unix_timestamp\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "* 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Build Version",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT version FROM (SELECT counter::field,\"release\"::tag,\"version\"::tag FROM \"cpanel_meta\" WHERE (\"url\" =~ /^$instance$/) ORDER BY time DESC LIMIT 1) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Version List",
     "type": "table",
     "description": "Show as table, incase multiple cPanel servers are listed to be viewed",
     "gridPos": { "h": 5, "w": 10, "x": 5, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpanel_start_time_unix_timestamp",
       "query": "SELECT last(counter::field),\"version\"::tag FROM \"cpanel_meta\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "* 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Active Used Plan Packages",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 45 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW TAG VALUES WITH key = plan WHERE (\"url\" =~ /^$instance$/)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Server Active Accounts Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_users_active\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Suspended Accounts Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_users_suspended\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Active Accounts Total Over Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_users_suspended",
       "query": "SELECT gauge FROM \"cpanel_users_active\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"\n",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Suspended Accounts Total Over Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_users_suspended",
       "query": "SELECT gauge FROM \"cpanel_users_suspended\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"\n",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Total FTP Accounts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(last_counter) AS \"FTP Accounts\" FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_ftp_accounts\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Total FTP Accounts Over Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT gauge FROM \"cpanel_ftp_accounts\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Domains",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Server Total Domains Configured",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_domains_configured\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Total Domains Configured Over TIme",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT gauge FROM \"cpanel_domains_configured\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Mail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Server Total Mailboxes Configured",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_mailboxes_configured\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Total Mailboxes Configured Over TIme",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT gauge FROM \"cpanel_mailboxes_configured\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Total Incoming/Outgoing Mail Exim Log Count",
     "type": "timeseries",
     "description": "Excludes mail count from base server's domain hostname.",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT gauge FROM \"cpanel_exim_log_outgoing_mail_count\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT gauge FROM \"cpanel_exim_log_incoming_mail_count\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Disk Device Utilization",
     "type": "table",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpanel_quota_percent",
       "query": "SELECT last(\"gauge\"), \"url\" FROM \"cpanel_disk_usage_percent\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\", \"disk\"::tag",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Total Disk Quota Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(last) FROM (SELECT last(gauge::field),\"user\"::tag FROM \"cpanel_quota_used\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter AND \"user\" =~ /$cpanel_user/ GROUP BY \"user\"::tag,\"url\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Disk Quota Usage By User",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "measurement": "cpanel_quota_percent",
       "query": "SELECT\n  MAX(\"gauge\") AS \"bandwidth\"\nFROM\n  \"cpanel_quota_percent\"\nWHERE\n  (\"url\" =~ /^$instance$/) AND\n  $timeFilter AND\n  (\"user\" =~ /$cpanel_user/)\nGROUP BY\n  time($__interval), \"user\"",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Highest Disk Quota Percentage Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpanel_quota_percent",
       "query": "SELECT max(\"gauge\"), \"url\" FROM \"cpanel_quota_percent\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter AND \"user\" =~ /$cpanel_user/ GROUP BY \"user\"::tag",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Disk Usage Worst Offenders",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(gauge) FROM \"cpanel_quota_used\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter AND \"user\" =~ /$cpanel_user/ group by \"user\",\"url\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Bandwidth Usage Worst Offenders",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(gauge) FROM \"cpanel_bandwidth\" WHERE (\"url\" =~ /^$instance$/) AND \"user\" =~ /$cpanel_user/ AND $timeFilter group by \"user\",\"url\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Total User Bandwidth Used Within Billing Period (cpanel uapi - Users with a bandwidth quota)",
     "type": "stat",
     "description": "Method: uapi",
     "gridPos": { "h": 4, "w": 11, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT\n    SUM(last) AS \"utilization\"\nFROM (\n    SELECT\n        LAST(\"gauge\")\n    FROM \"cpanel_bandwidth_user_used\"\n    WHERE (\"url\" =~ /^$instance$/)\n        AND $timeFilter\n        AND \"user\" =~ /$cpanel_user/\n    GROUP BY \"user\",\"url\"\n)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Total User Bandwidth Used Within Billing Period (cpanel bandwidth.cache - Includes users without a bandwidth quota)",
     "type": "stat",
     "description": "Method: bandwidth.cache",
     "gridPos": { "h": 4, "w": 11, "x": 10, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT\n    SUM(last) AS \"utilization\"\nFROM (\n    SELECT\n        LAST(\"gauge\")\n    FROM \"cpanel_bandwidth\"\n    WHERE (\"url\" =~ /^$instance$/)\n        AND $timeFilter\n       AND \"user\" =~ /$cpanel_user/\n    GROUP BY \"user\",\"url\"\n)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Bandwidth Usage Over Time Within Billing Period",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpanel_bandwidth",
       "query": "SELECT\n  MAX(\"gauge\") AS \"bandwidth\"\nFROM\n  \"cpanel_bandwidth\"\nWHERE\n  (\"url\" =~ /^$instance$/) AND\n  $timeFilter AND\n  (\"user\" =~ /$cpanel_user/)\nGROUP BY\n  time($__interval), \"user\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Bandwidth Usage Percent of User Over Time Within Billing Period",
     "type": "timeseries",
     "description": "This is their maximum bandwidth utilization from their plan. It's show as a percentage of bandwidth used of out of their maximum allowed.",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpanel_bandwidth",
       "query": "SELECT\n  MAX(\"gauge\") AS \"bandwidth\"\nFROM\n  \"cpanel_bandwidth_user_used_percent\"\nWHERE\n  (\"url\" =~ /^$instance$/) AND\n  $timeFilter AND\n  (\"user\" =~ /$cpanel_user/)\nGROUP BY\n  time($__interval), \"user\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Server CPU Load Average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT gauge FROM \"cpanel_system_load_average\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\", \"load\"::tag",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory (RAM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Server Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT gauge FROM \"cpanel_system_memory\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\", \"memory\"::tag",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "cPanel Server Total Active Email Sessions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_sessions_email\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Total Active Web Sessions (WHM & cPanel)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 5, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_sessions_web\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Total Active Email Sessions Over TIme",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT \"gauge\" FROM \"cpanel_sessions_email\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "cPanel Server Total Active Web Sessions (WHM & cPanel) Over TIme",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 5, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "cpanel_ftp_accounts",
       "query": "SELECT \"gauge\" FROM \"cpanel_sessions_web\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "systemd cpanel_exporter - go service metrics diagnostics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Column Category",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
     "options": {
      "content": "<p style=\"text-align: center;\"><strong>Go Metrics Service</strong></p>"
     }
    },
    {
     "title": "Go Metric Service Started",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process_start_time_seconds",
       "query": "SELECT last(\"gauge\") * 1000 FROM \"process_start_time_seconds\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "* 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Go Open File Descriptors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process_open_fds",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Go Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process_open_fds",
       "query": "SELECT last(\"gauge\") FROM \"process_open_fds\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval),url fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Go /metrics - Requests by response code",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "code" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "promhttp_metric_handler_requests_total",
       "query": "SELECT last(\"counter\") FROM \"promhttp_metric_handler_requests_total\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"code\", url fill(null)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Go CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_threads",
       "query": "SELECT last(\"gauge\") FROM \"go_threads\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), url fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Go Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Allocated bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "go_memstats_alloc_bytes",
       "query": "SELECT last(\"gauge\") FROM \"go_memstats_alloc_bytes\" WHERE $timeFilter GROUP BY time($__interval), url fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}