{
 "title": "cPanel Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "cPanel",
    "query": "SELECT DISTINCT(\"url\") FROM (SELECT * FROM \"cpanel_meta\" WHERE $timeFilter GROUP BY \"url\")"
   }
  ]
 },
 "panels": [
  {
   "title": "General Board Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"SHOW MEASUREMENTS\" that are available to use",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW MEASUREMENTS ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Field/Tags (cpanel_quota_percent)",
     "type": "table",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
     "targets": [
      {
       "query": "show tag keys from \"cpanel_quota_percent\""
      }
     ]
    },
    {
     "title": "Test Debug -- Field/Tags (cpanel_bandwidth",
     "type": "table",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
     "targets": [
      {
       "query": "show tag keys from \"cpanel_bandwidth\""
      }
     ]
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "cPanel Servers Selected",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "SELECT DISTINCT(\"url\") as \"Metric URL\" FROM (SELECT * FROM \"cpanel_meta\" WHERE $timeFilter AND (\"url\" =~ /^$instance$/) GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "Column Category",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 2 },
   "options": {
    "content": "<p style=\"text-align: center;\"><strong>General Counters and Counters over Time</strong></p>"
   }
  },
  {
   "title": "cPanel Active Accounts Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_users_active\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Column Category",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": {
    "content": "<p style=\"text-align: center;\"><strong>Go Metrics Service</strong></p>"
   }
  },
  {
   "title": "Column Category",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 4, "y": 8 },
   "options": {
    "content": "<p style=\"text-align: center;\"><strong>General Information</strong></p>"
   }
  },
  {
   "title": "cPanel Active Accounts Total Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "cpanel_users_suspended",
     "query": "SELECT gauge FROM \"cpanel_users_active\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"\n",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Metric Service Started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_start_time_seconds",
     "query": "SELECT last(\"gauge\") * 1000 FROM \"process_start_time_seconds\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Server Started Time Ago",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpanel_start_time_unix_timestamp",
     "query": "SELECT last(\"gauge\") * 1000 FROM \"process_start_time_seconds\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Server Started Date List",
   "type": "table",
   "description": "Show as table, incase multiple cPanel servers are listed to be viewed",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpanel_start_time_unix_timestamp",
     "query": "SELECT (last(gauge) * 1000) as \"Start Time\" FROM \"cpanel_start_time_unix_timestamp\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_open_fds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Suspended Accounts Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_users_suspended\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Build Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT version FROM (SELECT counter::field,\"release\"::tag,\"version\"::tag FROM \"cpanel_meta\" WHERE (\"url\" =~ /^$instance$/) ORDER BY time DESC LIMIT 1) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Server Version List",
   "type": "table",
   "description": "Show as table, incase multiple cPanel servers are listed to be viewed",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpanel_start_time_unix_timestamp",
     "query": "SELECT last(counter::field),\"version\"::tag FROM \"cpanel_meta\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Suspended Accounts Total Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "cpanel_users_suspended",
     "query": "SELECT gauge FROM \"cpanel_users_suspended\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"\n",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_open_fds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Total Disk Quota Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(last) FROM (SELECT last(gauge::field),\"user\"::tag FROM \"cpanel_quota_used\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"user\"::tag)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Active Used Plan Packages",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES WITH key = plan WHERE (\"url\" =~ /^$instance$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Total FTP Accounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(last_counter) AS \"FTP Accounts\" FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_ftp_accounts\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Go /metrics - Requests by response code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "promhttp_metric_handler_requests_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Column Category",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 4, "y": 27 },
   "options": {
    "content": "<p style=\"text-align: center;\"><strong>Additional Statistics</strong></p>"
   }
  },
  {
   "title": "cPanel Total FTP Accounts Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "cpanel_ftp_accounts",
     "query": "SELECT gauge FROM \"cpanel_ftp_accounts\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Total User Bandwidth Used Within Billing Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n    SUM(last) AS \"utilization\"\nFROM (\n    SELECT\n        LAST(\"gauge\")\n    FROM \"cpanel_bandwidth\"\n    WHERE (\"url\" =~ /^$instance$/)\n        AND $timeFilter\n    GROUP BY \"user\",\"url\"\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Go CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "go_threads",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Bandwidth Usage Worst Offenders",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(gauge) FROM \"cpanel_bandwidth\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter group by \"user\",\"url\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Total Domains Configured",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_domains_configured\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Total Domains Configured Over TIme",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "cpanel_ftp_accounts",
     "query": "SELECT gauge FROM \"cpanel_domains_configured\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Allocated bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "go_memstats_alloc_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Total User Bandwidth Used Within Billing Period",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"gauge\") FROM \"cpanel_bandwidth\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"user\",\"url\" ORDER BY time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Total Mailboxes Configured",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_mailboxes_configured\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Total Mailboxes Configured Over TIme",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "cpanel_ftp_accounts",
     "query": "SELECT gauge FROM \"cpanel_mailboxes_configured\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Disk Quota Usage By User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "measurement": "cpanel_quota_percent",
     "query": "SELECT gauge, \"user\"::tag FROM \"cpanel_quota_percent\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"user\"::tag ",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Highest Quota Percentage Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpanel_quota_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Bandwidth Usage Over Time Within Billing Period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpanel_bandwidth",
     "query": "SELECT MAX(gauge::field) FROM \"cpanel_bandwidth\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"user\"::tag, time(1h) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Bandwidth Usage Percent of User Over Time Within Billing Period",
   "type": "timeseries",
   "description": "This is their maximum bandwidth utilization from their plan. It's show as a percentage of bandwidth used of out of their maximum allowed.",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpanel_bandwidth",
     "query": "SELECT MAX(gauge::field) FROM \"cpanel_bandwidth_user_used_percent\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"user\"::tag, time(1h) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Column Category",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 4, "y": 73 },
   "options": {
    "content": "<p style=\"text-align: center;\"><strong>Active Sessions</strong></p>"
   }
  },
  {
   "title": "cPanel Total Active Email Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_sessions_email\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Total Active Web Sessions (WHM & cPanel)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(last_counter) FROM (SELECT last(gauge) AS \"last_counter\"  FROM \"cpanel_sessions_web\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY url)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cPanel Total Active Email Sessions Over TIme",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "cpanel_ftp_accounts",
     "query": "SELECT \"gauge\" FROM \"cpanel_sessions_email\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "cPanel Total Active Web Sessions (WHM & cPanel) Over TIme",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "cpanel_ftp_accounts",
     "query": "SELECT \"gauge\" FROM \"cpanel_sessions_web\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY \"url\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}